### ISSUE TITLE
A little help please?

### ISSUE THREAD

**Issue by canarvaeza** [ryanfb/pcl-tools#4]
Hello, 

I'm very new on c++ programming and i'm using the PCL to read some files and change it's format, i just download your code and make the cmake but when i debug it just open a comman window and closes after that. Don't store nothing...

What do i have to do to use your function?
Hope you can help me :smile: thanks.

**Comment by ryanfb** [comment]
I'm not really sure what problem you're running into - if you can copy/paste what you're running and the command line output I might be able to help.
